# Generated by Django 4.1.2 on 2022-10-09 14:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('position', models.CharField(max_length=100, verbose_name="Employee's Postion")),
                ('basic_rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name="Employee's Basic Rate")),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Project Name')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Site Name')),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee', verbose_name="DTR's Employee")),
            ],
            options={
                'db_table': 'payslips',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.site', verbose_name="Employee's Site"),
        ),
        migrations.CreateModel(
            name='DailyTimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name="DTR's Date")),
                ('time', models.DecimalField(decimal_places=1, max_digits=3, verbose_name="DTR's Time")),
                ('projects', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name="DTR's Projects'"), size=None)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payslip', verbose_name="DTR's Payslip")),
            ],
            options={
                'db_table': 'daily_time_records',
            },
        ),
    ]
