# Generated by Django 4.1.2 on 2022-10-16 07:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_projects_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=None), size=None),
        ),
    ]
