# Generated by Django 4.1.2 on 2022-11-04 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dailytimerecord',
            name='projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
