# Generated by Django 4.1.2 on 2022-11-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_employee_allowance_per_day_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.site', verbose_name="Employee's Site"),
        ),
    ]
