# Generated by Django 4.1.2 on 2022-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_employee_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, verbose_name="Project's Balance"),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, verbose_name="Project's Contact Price"),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default=None, max_length=100, verbose_name='Project Owner'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, verbose_name="Project's Total Payment"),
        ),
    ]
