# Generated by Django 4.1.2 on 2022-11-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_project_balance_project_contract_price_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name="Project's Balance"),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name="Project's Contact Price"),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name="Project's Total Payment"),
        ),
    ]
