# Generated by Django 4.1.2 on 2022-11-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_alter_project_balance_alter_project_contract_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name="Project's Contract Price"),
        ),
    ]
