# Generated by Django 4.1.2 on 2022-11-13 10:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_alter_project_contract_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=None),
        ),
    ]
