# Generated by Django 4.1.2 on 2022-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_remove_employee_allowance_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='basic_rate',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name="Employee's Basic Rate"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, null=True, verbose_name="Employee's Postion"),
        ),
    ]
