# Generated by Django 4.1.2 on 2022-11-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimerecord',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dailytimerecord',
            name='time',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_rate',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Basic Rate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Phone Number}'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, null=True, verbose_name=' Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Contract Price'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Total Payment'),
        ),
    ]
