# Generated by Django 4.1.2 on 2022-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_alter_dailytimerecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='allowance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Allowance'),
        ),
    ]
