# Generated by Django 4.1.2 on 2023-03-25 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_payslip_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='employees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
